### ISSUE TITLE
Error: Could not find class ::apache_c2c::params

### ISSUE THREAD

**Issue by kenorb** [camptocamp/puppet-nagios#30]
I'm using the following sample manifest:

    node 'default' {
      include nagios

      # It is possible to override all standard main configuration 
      # file options defined in template nagios.cfg.erb with prefix "nagios_"
      # 
      # $nagios_debug_level="-1"
      # $nagios_debug_verbosity="3"

      $nagiosadmin_password = "XXXX"

      include apache::base

      include nagios::base
      include nagios::webinterface
    }

However I've the error:

> Error: Could not find class `::apache_c2c::params` for debian-77-wheezy-64

I had also problem with `apache::base`:

> Error: Could not find class apache::base for debian-77-wheezy-64

Probably `apache::base` in README needs to be renamed to `apache_c2c::base` as suggested [here](http://serverfault.com/a/685460/130437).

I'm using puppet (v3.7.4), camptocamp-nagios (v1.0.4) and puppetlabs-apache (v1.2.0).

I'm using the right apache module (puppetlabs-apache)? Or what are the dependencies to use this module which I've missed?

**Comment by kenorb** [comment]
I think this is already addressed in [How to fix error: Could not find class apache::base?](http://serverfault.com/q/685456/130437).

Please confirm that I should install `camptocamp/puppet-apache_c2c` instead of `puppetlabs-apache`.

**Comment by mcanevet** [comment]
We're in the process of migrating to icinga and might deprecate this module at some point.
